spring.jpa.open-in-view=false
# exposing endpoints
management.endpoints.web.exposure.include=health,info,prometheus

# enables prometheus
management.endpoint.prometheus.enabled=true

# shows health details
management.endpoint.health.show-details=always